--[[[
@module Mage Environment Functions and Variables
@description
Mage Environment Functions and Variables.
]]--

--[[[
@module Mage
@description
Mage Spells.
GENERATED FROM WOWHEAD SPELLS - DO NOT EDIT MANUALLY
]]--

jps.spells.mage = {}
jps.spells.mage.invisibility = jps.toSpellName(66)
jps.spells.mage.frostbolt = jps.toSpellName(116)
jps.spells.mage.polymorph = jps.toSpellName(118)
jps.spells.mage.coneOfCold = jps.toSpellName(120)
jps.spells.mage.frostNova = jps.toSpellName(122)
jps.spells.mage.slowFall = jps.toSpellName(130)
jps.spells.mage.fireball = jps.toSpellName(133)
jps.spells.mage.arcaneExplosion = jps.toSpellName(1449)
jps.spells.mage.incantersFlow = jps.toSpellName(1463)
jps.spells.mage.blink = jps.toSpellName(1953)
jps.spells.mage.flamestrike = jps.toSpellName(2120)
jps.spells.mage.counterspell = jps.toSpellName(2139)
jps.spells.mage.scorch = jps.toSpellName(2948)
jps.spells.mage.teleportStormwind = jps.toSpellName(3561)
jps.spells.mage.teleportIronforge = jps.toSpellName(3562)
jps.spells.mage.teleportUndercity = jps.toSpellName(3563)
jps.spells.mage.teleportDarnassus = jps.toSpellName(3565)
jps.spells.mage.teleportThunderBluff = jps.toSpellName(3566)
jps.spells.mage.teleportOrgrimmar = jps.toSpellName(3567)
jps.spells.mage.arcaneMissiles = jps.toSpellName(5143)
jps.spells.mage.mageArmor = jps.toSpellName(6117)
jps.spells.mage.frostArmor = jps.toSpellName(7302)
jps.spells.mage.portalStormwind = jps.toSpellName(10059)
jps.spells.mage.pyroblast = jps.toSpellName(11366)
jps.spells.mage.portalIronforge = jps.toSpellName(11416)
jps.spells.mage.portalOrgrimmar = jps.toSpellName(11417)
jps.spells.mage.portalUndercity = jps.toSpellName(11418)
jps.spells.mage.portalDarnassus = jps.toSpellName(11419)
jps.spells.mage.portalThunderBluff = jps.toSpellName(11420)
jps.spells.mage.iceBarrier = jps.toSpellName(11426)
jps.spells.mage.coldSnap = jps.toSpellName(11958)
jps.spells.mage.arcanePower = jps.toSpellName(12042)
jps.spells.mage.evocation = jps.toSpellName(12051)
jps.spells.mage.icyVeins = jps.toSpellName(12472)
jps.spells.mage.masteryIgnite = jps.toSpellName(12846)
jps.spells.mage.shatter = jps.toSpellName(12982)
jps.spells.mage.spellsteal = jps.toSpellName(30449)
jps.spells.mage.arcaneBlast = jps.toSpellName(30451)
jps.spells.mage.iceLance = jps.toSpellName(30455)
jps.spells.mage.moltenArmor = jps.toSpellName(30482)
jps.spells.mage.slow = jps.toSpellName(31589)
jps.spells.mage.dragonsBreath = jps.toSpellName(31661)
jps.spells.mage.summonWaterElemental = jps.toSpellName(31687)
jps.spells.mage.portalExodar = jps.toSpellName(32266)
jps.spells.mage.portalSilvermoon = jps.toSpellName(32267)
jps.spells.mage.teleportExodar = jps.toSpellName(32271)
jps.spells.mage.teleportSilvermoon = jps.toSpellName(32272)
jps.spells.mage.teleportShattrath = jps.toSpellName(33690)
jps.spells.mage.portalShattrath = jps.toSpellName(33691)
jps.spells.mage.arcaneBarrage = jps.toSpellName(44425)
jps.spells.mage.livingBomb = jps.toSpellName(44457)
jps.spells.mage.flurry = jps.toSpellName(44614)
jps.spells.mage.iceBlock = jps.toSpellName(45438)
jps.spells.mage.teleportStonard = jps.toSpellName(49358)
jps.spells.mage.teleportTheramore = jps.toSpellName(49359)
jps.spells.mage.portalTheramore = jps.toSpellName(49360)
jps.spells.mage.portalStonard = jps.toSpellName(49361)
jps.spells.mage.teleportDalaranNorthrend = jps.toSpellName(53140)
jps.spells.mage.portalDalaranNorthrend = jps.toSpellName(53142)
jps.spells.mage.mirrorImage = jps.toSpellName(55342)
jps.spells.mage.splittingIce = jps.toSpellName(56377)
jps.spells.mage.glyphOfCrittermorph = jps.toSpellName(56382)
jps.spells.mage.masteryIcicles = jps.toSpellName(76613)
jps.spells.mage.timeWarp = jps.toSpellName(80353)
jps.spells.mage.frozenOrb = jps.toSpellName(84714)
jps.spells.mage.cauterize = jps.toSpellName(86949)
jps.spells.mage.teleportTolBarad = jps.toSpellName(88342)
jps.spells.mage.portalTolBarad = jps.toSpellName(88345)
jps.spells.mage.iceFloes = jps.toSpellName(108839)
jps.spells.mage.fireBlast = jps.toSpellName(108853)
jps.spells.mage.greaterInvisibility = jps.toSpellName(110959)
jps.spells.mage.frostBomb = jps.toSpellName(112948)
jps.spells.mage.fingersOfFrost = jps.toSpellName(112965)
jps.spells.mage.ringOfFrost = jps.toSpellName(113724)
jps.spells.mage.netherTempest = jps.toSpellName(114923)
jps.spells.mage.runeOfPower = jps.toSpellName(116011)
jps.spells.mage.criticalMass = jps.toSpellName(117216)
jps.spells.mage.ancientTeleportDalaran = jps.toSpellName(120145)
jps.spells.mage.ancientPortalDalaran = jps.toSpellName(120146)
jps.spells.mage.illusion = jps.toSpellName(131784)
jps.spells.mage.portalValeOfEternalBlossoms = jps.toSpellName(132620)
jps.spells.mage.teleportValeOfEternalBlossoms = jps.toSpellName(132621)
jps.spells.mage.waterJet = jps.toSpellName(135029)
jps.spells.mage.glyphOfEvaporation = jps.toSpellName(146662)
jps.spells.mage.glyphOfTheUnboundElemental = jps.toSpellName(146976)
jps.spells.mage.meteor = jps.toSpellName(153561)
jps.spells.mage.cometStorm = jps.toSpellName(153595)
jps.spells.mage.arcaneOrb = jps.toSpellName(153626)
jps.spells.mage.overpowered = jps.toSpellName(155147)
jps.spells.mage.kindling = jps.toSpellName(155148)
jps.spells.mage.thermalVoid = jps.toSpellName(155149)
jps.spells.mage.enhancedPyrotechnics = jps.toSpellName(157642)
jps.spells.mage.unstableMagic = jps.toSpellName(157976)
jps.spells.mage.supernova = jps.toSpellName(157980)
jps.spells.mage.blastWave = jps.toSpellName(157981)
jps.spells.mage.iceNova = jps.toSpellName(157997)
jps.spells.mage.teleportWarspear = jps.toSpellName(176242)
jps.spells.mage.portalWarspear = jps.toSpellName(176244)
jps.spells.mage.portalStormshield = jps.toSpellName(176246)
jps.spells.mage.teleportStormshield = jps.toSpellName(176248)
jps.spells.mage.blastingRod = jps.toSpellName(187258)
jps.spells.mage.aegwynnsImperative = jps.toSpellName(187264)
jps.spells.mage.etherealSensitivity = jps.toSpellName(187276)
jps.spells.mage.aegwynnsFury = jps.toSpellName(187287)
jps.spells.mage.everywhereAtOnce = jps.toSpellName(187301)
jps.spells.mage.torrentialBarrage = jps.toSpellName(187304)
jps.spells.mage.cracklingEnergy = jps.toSpellName(187310)
jps.spells.mage.arcanePurification = jps.toSpellName(187313)
jps.spells.mage.mightOfTheGuardians = jps.toSpellName(187318)
jps.spells.mage.aegwynnsWrath = jps.toSpellName(187321)
jps.spells.mage.aegwynnsAscendance = jps.toSpellName(187680)
jps.spells.mage.arcaneRebound = jps.toSpellName(188006)
jps.spells.mage.combustion = jps.toSpellName(190319)
jps.spells.mage.conjureRefreshment = jps.toSpellName(190336)
jps.spells.mage.blizzard = jps.toSpellName(190356)
jps.spells.mage.arcaneCharge = jps.toSpellName(190427)
jps.spells.mage.brainFreeze = jps.toSpellName(190447)
jps.spells.mage.masterySavant = jps.toSpellName(190740)
jps.spells.mage.teleportHallOfTheGuardian = jps.toSpellName(193759)
jps.spells.mage.fireAtWill = jps.toSpellName(194224)
jps.spells.mage.reignitionOverdrive = jps.toSpellName(194234)
jps.spells.mage.pyroclasmicParanoia = jps.toSpellName(194239)
jps.spells.mage.burningGaze = jps.toSpellName(194312)
jps.spells.mage.greatBallsOfFire = jps.toSpellName(194313)
jps.spells.mage.everburningConsumption = jps.toSpellName(194314)
jps.spells.mage.moltenSkin = jps.toSpellName(194315)
jps.spells.mage.cauterizingBlink = jps.toSpellName(194318)
jps.spells.mage.pyreticIncantation = jps.toSpellName(194331)
jps.spells.mage.aftershocks = jps.toSpellName(194431)
jps.spells.mage.phoenixsFlames = jps.toSpellName(194466)
jps.spells.mage.blastFurnace = jps.toSpellName(194487)
jps.spells.mage.icyCaress = jps.toSpellName(195315)
jps.spells.mage.iceAge = jps.toSpellName(195317)
jps.spells.mage.letItGo = jps.toSpellName(195322)
jps.spells.mage.orbitalStrike = jps.toSpellName(195323)
jps.spells.mage.frozenVeins = jps.toSpellName(195345)
jps.spells.mage.clarityOfThought = jps.toSpellName(195351)
jps.spells.mage.theStormRages = jps.toSpellName(195352)
jps.spells.mage.shieldOfAlodi = jps.toSpellName(195354)
jps.spells.mage.chainReaction = jps.toSpellName(195419)
jps.spells.mage.chilledToTheCore = jps.toSpellName(195448)
jps.spells.mage.blackIce = jps.toSpellName(195615)
jps.spells.mage.displacement = jps.toSpellName(195676)
jps.spells.mage.quickening = jps.toSpellName(198923)
jps.spells.mage.cinderstorm = jps.toSpellName(198929)
jps.spells.mage.glacialSpike = jps.toSpellName(199786)
jps.spells.mage.pyromaniac = jps.toSpellName(205020)
jps.spells.mage.rayOfFrost = jps.toSpellName(205021)
jps.spells.mage.arcaneFamiliar = jps.toSpellName(205022)
jps.spells.mage.conflagration = jps.toSpellName(205023)
jps.spells.mage.lonelyWinter = jps.toSpellName(205024)
jps.spells.mage.presenceOfMind = jps.toSpellName(205025)
jps.spells.mage.firestarter = jps.toSpellName(205026)
jps.spells.mage.boneChilling = jps.toSpellName(205027)
jps.spells.mage.resonance = jps.toSpellName(205028)
jps.spells.mage.flameOn = jps.toSpellName(205029)
jps.spells.mage.frozenTouch = jps.toSpellName(205030)
jps.spells.mage.chargedUp = jps.toSpellName(205032)
jps.spells.mage.controlledBurn = jps.toSpellName(205033)
jps.spells.mage.wordsOfPower = jps.toSpellName(205035)
jps.spells.mage.iceWard = jps.toSpellName(205036)
jps.spells.mage.flamePatch = jps.toSpellName(205037)
jps.spells.mage.arcticGale = jps.toSpellName(205038)
jps.spells.mage.erosion = jps.toSpellName(205039)
jps.spells.mage.arcaneLinguist = jps.toSpellName(210086)
jps.spells.mage.blueFlameSpecial = jps.toSpellName(210182)
jps.spells.mage.manaShield = jps.toSpellName(210716)
jps.spells.mage.touchOfTheMagi = jps.toSpellName(210725)
jps.spells.mage.markOfAluneth = jps.toSpellName(210726)
jps.spells.mage.sloooowDown = jps.toSpellName(210730)
jps.spells.mage.artificialStamina = jps.toSpellName(211309)
jps.spells.mage.shimmer = jps.toSpellName(212653)
jps.spells.mage.jouster = jps.toSpellName(214626)
jps.spells.mage.shatteringBolts = jps.toSpellName(214629)
jps.spells.mage.ebonbolt = jps.toSpellName(214634)
jps.spells.mage.iceNine = jps.toSpellName(214664)
jps.spells.mage.itsColdOutside = jps.toSpellName(214776)
jps.spells.mage.ancientPower = jps.toSpellName(214917)
jps.spells.mage.empoweredSpellblade = jps.toSpellName(214918)
jps.spells.mage.spellborne = jps.toSpellName(214919)
jps.spells.mage.ruleOfThrees = jps.toSpellName(215463)
jps.spells.mage.phoenixReborn = jps.toSpellName(215773)
jps.spells.mage.bigMouth = jps.toSpellName(215796)
jps.spells.mage.glyphOfSparkles = jps.toSpellName(219573)
jps.spells.mage.glyphOfSmolder = jps.toSpellName(219592)
jps.spells.mage.glyphOfPolymorphicProportions = jps.toSpellName(219630)
jps.spells.mage.icyHand = jps.toSpellName(220817)
jps.spells.mage.wingsOfFlame = jps.toSpellName(221844)
jps.spells.mage.teleportDalaranBrokenIsles = jps.toSpellName(224869)
jps.spells.mage.portalDalaranBrokenIsles = jps.toSpellName(224871)
jps.spells.mage.scorchedEarth = jps.toSpellName(227481)
jps.spells.mage.arcaneInstability = jps.toSpellName(166872)
jps.spells.mage.potentFlames = jps.toSpellName(145254)
jps.spells.mage.heatingUp = jps.toSpellName(48107)
jps.spells.mage.pyromaniac = jps.toSpellName(166868)
jps.spells.mage.ignite = jps.toSpellName(101166)
jps.spells.mage.waterJet = jps.toSpellName(135029)
jps.spells.mage.hotStreak = jps.toSpellName(48108)



local burnPhase = false
function jps.burnPhase()
    if not burnPhase then
        -- At the start of the fight and whenever Evocation Icon Evocation is about to come off cooldown, you need to start the Burn Phase
        -- and burn your Mana. Before doing so, make sure that you have 3 charges of Arcane Missiles and 4 stacks of Arcane Charge.
        burnPhase = jps.timeInCombat() < 5 or jps.cooldown(jps.spells.mage.evocation) < 2
    else
        burnPhase = jps.mana > 0.35
    end
    return burnPhase
end




